### ISSUE TITLE
doesn't encode empty bytes properly?

### ISSUE THREAD

**Issue by oconnor663** [keis/base58#1]
I think the empty byte string `b''` should encode to the empty string `""`. Instead, it currently encodes to `"11"`.

Similarly, the string `"1"` should decode to the byte `b'\x00'`. Instead, it currently decodes to `b'\x00\x00'`.

I'm not totally sure about the right behavior for Base58 padding, but I think at least it should be possible to round-trip any string of bytes. Right now if you send any number of zero-bytes (including the empty bytestring) through encode+decode, you get a different number of bytes back out.

**Comment by keis** [comment]
Hi.

Thanks for the report. Fixing the encoding of empty buffer should be pretty easy I think. I'll see if I can add some fuzzing tests for validating the round-trip.

**Comment by keis** [comment]
should be fixed now. would you mind giving `master` a spin before I cut a release?

**Comment by oconnor663** [comment]
Works for me. I threw in another (few hundred) round trip tests in a loop just in case: https://github.com/keis/base58/pull/3

**Comment by keis** [comment]
The freshly cut 0.2.2 release has this fix now :)

**Comment by oconnor663** [comment]
Awesome, thanks.
