### ISSUE TITLE
output as a byte array

### ISSUE THREAD

**Issue by TKorr** [keis/base58#15]
currently your encode function spits out a string, which is annoying because I have to wrap the output in the str.encode() method.

**Comment by keis** [comment]
yeah, ack, it's a very annoying quirk that has been present from when I first added python3 support. Changing to bytes would make sense but I've been hesitant to break things in subtle ways for something that is at worst an annoyance.

Are you using python2 or 3 btw?

**Comment by TKorr** [comment]
python3, know of any decent workarounds?

**Comment by keis** [comment]
nothing except doing encode() as you mention. But maybe I'm not understanding your problem correctly if that's not decent.

**Comment by fametrano** [comment]
I would prefer encode/decode to have same output type. I also have a slight preference for bytes.

**Comment by dheera** [comment]
Agree with this, for consistency and interchangeability with base64 and whatever other baseX come out in the future.
![2017-12-09 20-25-35](https://user-images.githubusercontent.com/1786477/33799213-2a72a3e0-dcdc-11e7-8e42-c3b419928142.png)
