### ISSUE TITLE
Command line program should not strip trailing newlines

### ISSUE THREAD

**Issue by pezcore** [keis/base58#24]
The command line program strips trailing newlines from the input data to be encoded:

https://github.com/keis/base58/blob/24372afd895a72ccbe5e5d399d146b7de4431b0e/base58.py#L149

This is not desired because when encoding data, this prevents correct encoding of binary data (such as a HASH160 digest) which can end in a newline char. For example, if I wanted to encode the bitcoin address [1FdHgMWo5rWRDcxp6ygqq64TaWZR9qFzwv](https://blockchain.info/address/1FdHgMWo5rWRDcxp6ygqq64TaWZR9qFzwv), and I fed the codec the pubkeyhash for this address `0xa06ea87a68cc6e0ea5816e9d9cbcd776d07cbd0a`, it would strip the trailing newline byte `0x0a` resulting an a totally incorrect b58check encoded string.

**Comment by keis** [comment]
Thanks for the heads up. This has bugged me for some time but didn't realise it was that critical.
