### ISSUE TITLE
b58encode() and b58encode_int() output differs

### ISSUE THREAD

**Issue by gruns** [keis/base58#30]
Example code:

```python
>>> b = b'\x00\x81\x1a\xba\x18\x9fB\xee\x9d\xe3\nR2\xf7u\xbc'
>>> i = int(b.hex(), 16)
>>> b58encode(b)
b'14cVa7ENbANHf5WGzDC8VH'
>>> b58encode_int(i)
b'4cVa7ENbANHf5WGzDC8VH'
```

They decode properly

```python
>>> b58decode(b58encode(b)) == b
True
>>> b58decode_int(b58encode_int(i)) == i
True
```

From my explorations, the output of `b58encode()` and `b58encode_int()` only
differs when the byte string has prefix `\0`s.

 * https://github.com/keis/base58/blob/master/base58.py#L63

appears the culprit.

The output of `b58encode()` and `b58encode_int()` should be identical, right?

**Comment by gruns** [comment]
Confirmed: The outputs of `b58encode()` and `b58encode_int()` are identical when
leading `\0`s aren't stripped in `b58encode()`. I.e. if 

 * https://github.com/keis/base58/blob/master/base58.py#L63

is commented out.

```python
ic| b58encode_int(i):        b'4cVa7ENbANHf5WGzDC8VH'
ic| b58encode_nostrip(b):    b'4cVa7ENbANHf5WGzDC8VH'
```

**Comment by keis** [comment]
Hey @gruns 
This special encoding of leading zeros is intended and part of how the reference for this flavor of base58 works (bitcoin). If you try to decode the output of _int or your _nostrip variant you will see they have discarded the leading 0 byte.

```
In [6]: b58decode(b'4cVa7ENbANHf5WGzDC8VH')
Out[6]: b'\x81\x1a\xba\x18\x9fB\xee\x9d\xe3\nR2\xf7u\xbc'
```

**Comment by gruns** [comment]
> This is by design. If an integer is fed, without additional context the
> program cannot know how many bytes you expect it to process, only how many are
> non-zero in the integer.

Right.

```python
>>> b58encode_int(0)
b'1'
>>> b58encode(bytes(bytearray.fromhex('00' * 16)))
b'1111111111111111'
```

> The base58 spec says that 1 prefixes are ignorables.

Cool. So prefix `1`s are throwaway and are thusly dropped, resulting in shorter
encoder output.

Thank your time, help, and clarification @gappleto97 and @keis. Cheers.

**Comment by gappleto97** [comment]
No problem. Feel free to hit me up if you have more questions.
