### ISSUE TITLE
Source code change yields different result

### ISSUE THREAD

**Issue by jay754** [keis/base58#4]
Hi,

On line 44, if I change the,

acc, mod = divmod(acc, 58),

into ->

acc = divmod(acc, 58)[0]
mod = divmod(acc, 58)[1]

I get a different result than the once provided in the test.

Is there a reason for this?

**Comment by keis** [comment]
In your 2nd example `acc` is changed between the calls to divmod

**Comment by jay754** [comment]
Facepalm. Thanks
