### ISSUE TITLE
b58encode_check does not take a str as input

### ISSUE THREAD

**Issue by hukkinj1** [keis/base58#45]
b58encode_check only takes `bytes` as input. This is inconsistent with b58encode, which can handle a `Union[str, bytes]` as input.

**Comment by hukkinj1** [comment]
Maybe the proper fix is to throw a `TypeError` for `b58encode("string")` calls though, and only allow `bytes` for that too. That is a breaking change however.

**Comment by keis** [comment]
This is a very persistent topic. Originally it was operating on str which I think was a mistake, the promoted usage is bytes in bytes out. Supporting str has been requested before and I think by now there's probably a lot of code using that. I agree it would be more proper to simply go only bytes but I still prefer the pragmatic option of adding scrub input to this call too.

For reference #15 #16 #27
