### ISSUE TITLE
Python 3 encode TypeError.

### ISSUE THREAD

**Issue by zkanda** [keis/base58#5]
Hello,

I'm getting this error on `Python 3.5.1`

```
TypeError: lstrip arg must be None or str
```

It's very easy to reproduce it.

```
import base58
base58.b58encode("test")
```

**Comment by keis** [comment]
Just like the base64 module it's intended to be used with bytes arguments and not str() because the encoding is defined in terms of byte level manipulation.

But I'll give you that the error message is horrible
