### ISSUE TITLE
The code may be simplified using int.from_bytes()

### ISSUE THREAD

**Issue by kolomenkin** [keis/base58#51]
The code may be simplified using int.from_bytes().
The proposed change makes the code more simple.
And I hope it will become faster.

Original code:
```
    p, acc = 1, 0
    for c in reversed(v):
        acc += p * c
        p = p << 8
```

My code instead:
```
    acc = int.from_bytes(v, byteorder='big')
```

I would also propose to rename variable `acc` after this change.

This change will need Python 3.2 at least:
https://docs.python.org/3.2/library/stdtypes.html?highlight=set#int.from_bytes

**Comment by keis** [comment]
Nice catch!

With python 2 support being dropped this could indeed be used, I've not given much consideration to what minimum version of python 3 should be supported but 3.2 should be good.

Will you create a PR?

**Comment by kolomenkin** [comment]
Please look into this draft PR:
https://github.com/keis/base58/pull/53
