### ISSUE TITLE
Add more Fault Tolerance

### ISSUE THREAD

**Issue by LuminousXLB** [keis/base58#54]
Would you like to add some fault tolerance such as automatically change `l` to `1`?

**Comment by keis** [comment]
That's an interesting idea! I could see a feature like that making sense but it should probably be optional.

there's also the question on how to deal with different alphabets because all the fixes may not apply to all of them

**Comment by gappleto97** [comment]
I feel like the way to go on this would be to have an argument like `fix_lookalike`, and if it's true to apply some regexes or if statements to the alphabet. That way if you don't cover all cases they can just not use it.

**Comment by LuminousXLB** [comment]
I appreciate the idea of `fix_lookalike`.
And for the implementation, it might be better to give a map table, which maps '1' and 'l' to the same integer. It might be something like [this](https://github.com/luke-jr/libbase58/blob/master/base58.c#L24-L33)

**Comment by keis** [comment]
With the changes proposed in #53 adding a pass to modify the map with these fixes should be simple enough.

so there are a couple of character sets  `1l` `oO0` that can be fixed as long as only one of the elements are in the alphabet. Any other characters that could get fixed?

**Comment by gappleto97** [comment]
`Il` as well. Maybe `4A`, depending on font?

**Comment by LuminousXLB** [comment]
For the bitcoin style, here's a [reference](https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch04.asciidoc#base58)

>`123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz`

> Or, more simply, it is a set of lowercase and capital letters and numbers without the four (0, O, l, I) just mentioned.

That's to say `0` , `O` should be mapped to `o` and `I`, `l` should be mapped to `1`.

**Comment by LuminousXLB** [comment]
Shall we merge #53 firstly and then we can modify on it?

**Comment by keis** [comment]
@LuminousXLB yeah, that seems to be the best way
