### ISSUE TITLE
How to decode to an array of decimals?

### ISSUE THREAD

**Issue by oboxodo** [keis/base58#68]
I'm sorry this is more a support request than an issue in the code. Couldn't find a better place to ask about this.

I'm executing this on the command line:
```sh
echo "4AfmonCVDRutyt3vMfsooagRsoNXTCVURGZ7nzSZPP9CWykXUmgA72Sfgrne7EcqtVJE6Gq6aA8xw21bHtbZMQzL" | base58 -d
```

And the output is:
```
�c�+�w�	���0��s-C��ǂг��) ��3��A@G�w뽝1A楡��Mՙ�#�Y
```

I'd like to get an array of decimals instead, just like the following code using `base58` as a package and not from the command line:

(working example taken from https://stackoverflow.com/a/69256259)

```python
import base58
MY_PRIVATE_KEY_IN_BASE58="4AfmonCVDRutyt3vMfsooagRsoNXTCVURGZ7nzSZPP9CWykXUmgA72Sfgrne7EcqtVJE6Gq6aA8xw21bHtbZMQzL"
byte_array = base58.b58decode(MY_PRIVATE_KEY_IN_BASE58)
json_string = "[" + ",".join(map(lambda b: str(b), byte_array)) + "]"
print(json_string)
```

Executing that outputs an array of integers:

```json
[158,99,132,43,140,119,254,9,6,225,141,208,225,184,48,219,246,115,45,3,0,67,160,190,25,199,130,208,179,210,219,1,41,32,144,228,51,198,235,65,64,71,155,119,235,189,157,49,2,65,230,165,161,159,153,77,213,153,226,174,35,2,212,89]
```

Do you know what normal unix/linux command line utility I could use to pipe base58's output into and at least print the list of decimals instead of the gibberish text?

**Comment by keis** [comment]
Hey, the gibberish text you're seeing is your terminal trying to display the binary content that was encoded. Pipe that to a hexdump and you can get something human readable. Or if you specifically want the bytes encoded in decimal for some reason try `base58 -d | od -tu1`
