### ISSUE TITLE
demonstrate python3 support to the caniusepython3 package

### ISSUE THREAD

**Issue by dtenenba** [keis/base58#7]
Clearly your project works on python 3 since it is passing tests on Travis in both python 2 and 3. However, the site [CanIusePython3](https://caniusepython3.com/project/base58) says that this package does not work on python 3. The way to demonstrate python 3 support is documented [here](https://github.com/brettcannon/caniusepython3#how-do-you-tell-if-a-project-has-been-ported-to-python-3), basically you need to pass an appropriate trove classifier in `setup.py`, in a `classifier` argument to `setup()`.

A working example is [here](https://github.com/boto/boto3/blob/develop/setup.py#L47-L60).

**Comment by keis** [comment]
Hi @dtenenba 

The code does indeed work on python 3. I'll take a look at adding some classifiers and then cutting a new release to get this onto pypi

**Comment by keis** [comment]
Fixed!
